version: "3.4"

services:
  symfony-web-application:
    build:
      context: .
      target: symfony-web-application
    volumes:
      - .:/app
    stop_grace_period: 0s
    ports:
      - 8000:8000

  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
      - ./docker/db/files:/home:rw
    ports:
      - 5432:5432
